export enum PrefixType {
  MR = "MR",
  MS = "MS",
  MRS = "MRS",
  OTHER = "OTHER",
}

export enum FacultyId {
  FACULTY_OF_EDUCATION = "FACULTY_OF_EDUCATION", // คณะครุศาสตร์
  FACULTY_OF_PSYCHOLOGY = "FACULTY_OF_PSYCHOLOGY", // คณะจิตวิทยา
  FACULTY_OF_DENTISTRY = "FACULTY_OF_DENTISTRY", // คณะทันตแพทยศาสตร์
  FACULTY_OF_LAW = "FACULTY_OF_LAW", // คณะนิติศาสตร์
  FACULTY_OF_COMMUNICATION_ARTS = "FACULTY_OF_COMMUNICATION_ARTS", // คณะนิเทศศาสตร์
  FACULTY_OF_NURSING = "FACULTY_OF_NURSING", // คณะพยาบาลศาสตร์
  FACULTY_OF_COMMERCE_AND_ACCOUNTANCY = "FACULTY_OF_COMMERCE_AND_ACCOUNTANCY", // คณะพาณิชยศาสตร์และการบัญชี
  FACULTY_OF_MEDICINE = "FACULTY_OF_MEDICINE", // คณะแพทยศาสตร์
  FACULTY_OF_PHAMACEUTICAL_SCIENCE = "FACULTY_OF_PHAMACEUTICAL_SCIENCE", // คณะเภสัชศาสตร์
  FACULTY_OF_POLITICAL_SCIENCE = "FACULTY_OF_POLITICAL_SCIENCE", // คณะรัฐศาสตร์
  FACULTY_OF_SCIENCE = "FACULTY_OF_SCIENCE", // คณะวิทยาศาสตร์
  FACULTY_OF_SPORTS_SCIENCE = "FACULTY_OF_SPORTS_SCIENCE", // คณะวิทยาศาสตร์การกีฬา
  FACULTY_OF_ENGINEERING = "FACULTY_OF_ENGINEERING", // คณะวิศวกรรมศาสตร์
  FACULTY_OF_FINE_AND_APPLIED_ARTS = "FACULTY_OF_FINE_AND_APPLIED_ARTS", // คณะศิลปกรรมศาสตร์
  FACULTY_OF_ECONOMICS = "FACULTY_OF_ECONOMICS", // คณะเศรษฐศาสตร์
  FACULTY_OF_ARCHITECTURE = "FACULTY_OF_ARCHITECTURE", // คณะสถาปัตยกรรมศาสตร์
  FACULTY_OF_ALLIED_HEALTH_SCIENCES = "FACULTY_OF_ALLIED_HEALTH_SCIENCES", // คณะสหเวชศาสตร์
  FACULTY_OF_VETERINARY_SCIENCE = "FACULTY_OF_VETERINARY_SCIENCE", // คณะสัตวแพทยศาสตร์
  FACULTY_OF_ARTS = "FACULTY_OF_ARTS", // คณะอักษรศาสตร์
  SCHOOL_OF_INTEGRATED_INNOVATION_SCII = "SCHOOL_OF_INTEGRATED_INNOVATION_SCII", // สถาบันนวัตกรรมบูรณาการแห่งจุฬาลงกรณ์มหาวิทยาลัย
  SCHOOL_OF_AGRICULTURAL_RESOURCES = "SCHOOL_OF_AGRICULTURAL_RESOURCES", // สำนักวิชาทรัพยากรการเกษตร
  GRADUATE_SCHOOL = "GRADUATE_SCHOOL", // บัณฑิตวิทยาลัย
}

export enum RoleType {
  STAFF = "STAFF",
  FRESHMAN = "FRESHMAN",
}

export enum EventType {
  FIRSTDATE = "FIRSTDATE",
  RPKM = "RPKM",
  FRESHMENNIGHT = "FRESHMENNIGHT",
}

export enum CheckinStatusType {
  PRE_REGISTER = "PRE_REGISTER",
  EVENT_REGISTER = "EVENT_REGISTER",
}

export enum HouseSizeType {
  S = "S",
  M = "M",
  L = "L",
  XL = "XL",
  XXL = "XXL",
}

export enum GroupRoleType {
  OWNER = "OWNER",
  MEMBER = "MEMBER",
}

export enum WorkshopType {
  DIFFUSER = "DIFFUSER",
  KEYCHAIN = "KEYCHAIN",
}
